version: '3'
volumes:
  pgdata:
  pgadmin:
services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_PASS}
      POSTGRES_PASS: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"

      # - VIRTUAL_HOST=${PGADMIN_DOMAIN}
      # - VIRTUAL_PORT=${PGADMIN_PORT}
      # - LETSENCRYPT_HOST=${PGADMIN_DOMAIN}
      # - LETSENCRYPT_EMAIL=${EMAIL}
    ports:
      - 9124:${PGADMIN_PORT}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres_network
    expose:
      - "${PGADMIN_PORT}"
networks:
  postgres_network:
    external: true