version: '3'
volumes:
  pgdata:
  static_files:
  pgadmin:
services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_PASS}
      POSTGRES_PASS: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    links:
      - python
    networks:
      - webtools
  python: &python
    # image: python:3.4
    image: mertenssander/nictiz_webtools:latest
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.base
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/webserver/static_files
    command: gunicorn -w 4 app.wsgi -b 0.0.0.0:8000 --timeout 300
    networks:
      - webtools
  
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/webserver/static_files
    links:
      - python
    # ports:
    #   - ${PORT}:${PORT}
    expose:
      - "${PORT}"
    networks:
      - webtools
      - proxy
    environment:
      - VIRTUAL_HOST=${DJANGO_DOMAIN}
      - VIRTUAL_PORT=${PORT}
      - LETSENCRYPT_HOST=${DJANGO_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

  ## RabbitMQ as message queue for Celery
  rabbitmq:
    image: rabbitmq:3.7-alpine
    networks:
      - webtools
  celery_worker:
    # Copy template from service Python
    <<: *python
    command: celery -A app worker --scheduler django --loglevel=info
    ports: []
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - webtools
  celery_beat:
    # Copy template from service Python
    <<: *python
    command: celery -A app beat --loglevel info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    ports: []
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - webtools
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - webtools
      - proxy
    expose:
      - "${PGADMIN_PORT}"
    # environment:
    #   - VIRTUAL_HOST=${PGADMIN_DOMAIN}
    #   - VIRTUAL_PORT=${PGADMIN_PORT}
    #   - LETSENCRYPT_HOST=${PGADMIN_DOMAIN}
    #   - LETSENCRYPT_EMAIL=${EMAIL}
  # GUI for taskmanager Celery
  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://guest:guest@rabbitmq/", "--port=8888", "--basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"]
    restart: always
    expose:
      - "${FLOWER_PORT}"
    # environment:
    #   - VIRTUAL_HOST=${FLOWER_DOMAIN}
    #   - VIRTUAL_PORT=${FLOWER_PORT}
    #   - LETSENCRYPT_HOST=${FLOWER_DOMAIN}
    #   - LETSENCRYPT_EMAIL=${EMAIL}
    # ports:
    #   - ${FLOWER_PORT}:${FLOWER_PORT}
    networks:
      - webtools
      - proxy
networks:
  webtools:
  proxy:
    external: true