version: '3'
volumes:
  node_modules:
services:
  nodejs:
    build:
      context: './node'
      dockerfile: 'Dockerfile_prod'
    environment:
      - VIRTUAL_HOST=${NODE_DOMAIN}
      - VIRTUAL_PORT=${NODE_PORT}
      - LETSENCRYPT_HOST=${NODE_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

    # ports:
    #   - '9123:8080'
    expose:
      - 80
    networks:
      - proxy
networks:
  webtools:
  proxy:
    external: true