version: '3'
volumes:
  pgdata:
  pgadmin:
services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_PASS}
      POSTGRES_PASS: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
    ports:
      - 9124:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres_network
    expose:
      - 80
networks:
  postgres_network:
    external: true